### ISSUE TITLE
SOLUTION:  (for Twitter source) Error:  ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by mjasek114** [abessou/w251-FinalProject#21]
Here is one possible solution to this error.
**Solution 1:**
- You might have a suspended job running in the background on Unix.  To find out type 'jobs' to find out.  If it outputs something like:  [1]-  Stopped  python DataIngest.py --config t-l.cfg.  Then you need to kill that job before running DataIngest again.
- Kill the job with 'kill %<job number>'  In the above case 'kill %1'
- You might get a suspended job if you use Ctrl-z instead of Ctrl-c to stop your python job.  Ctrl-c kills a job.  Ctrl-z suspends/stops a job.  ALWAYS USE Ctrl-c

**Solution 2:**
For Twitter:  This error will also happen if you have spaces between the track terms in your config file.
Wrong:  track=music, entertainment, video
Right:  track=music,entertainment,video

**Error:**
[root@FinalProject251 code]# python DataIngest.py --config t-l.cfg
Creating Twitter source (found [Twitter] section)
Creating Local sink (found [Local] section)
[Local] Writing to folder /root/fp251/w205-data-ingest/twitterdata/2016-03-12T21:12:22.591384-51c2ea46-ca51-4ff1-8ea7-74320492fa5f
Traceback (most recent call last):
  File "DataIngest.py", line 167, in <module>
    main()
  File "DataIngest.py", line 36, in main
    ingest.start_collection()
  File "DataIngest.py", line 164, in start_collection
    self.sinks[0].write(self.sources[0])
  File "/root/w251-FinalProject/code/sinks/LocalDataIngestSink.py", line 54, in write
    for item in source:
  File "/root/w251-FinalProject/code/sources/TwitterDataIngestSource.py", line 37, in next
    return { 'tweet' : json.loads(self.source_iterator.next()) }
  File "/usr/local/anaconda2/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mjasek114** [comment]
Wrote up this issue and closed it in case it happens to someone else.
